CREATE TABLE DEPARTMENT
(
    did INTEGER PRIMARY KEY,
    descr VARCHAR(50) NOT NULL,
    title VARCHAR(50) NOT NULL
);

INSERT INTO DEPARTMENT VALUES (1,'FINANCE','ACCOUNTANT');
INSERT INTO DEPARTMENT VALUES (2,'FINANCE','MANAGER');
INSERT INTO DEPARTMENT VALUES (3,'IT','PROGRAMMER');
INSERT INTO DEPARTMENT VALUES (4,'BOSS','VICE PRESIDENT');

CREATE TABLE EMPLOYEE
(
    id INTEGER PRIMARY KEY,
    firstName VARCHAR(50) NOT NULL,
    lastName VARCHAR(50) NOT NULL,
    email VARCHAR(50) NOT NULL,
    address VARCHAR(50) NOT NULL,
    did INTEGER NOT NULL,
    salary NUMBER,
    FOREIGN KEY(did) REFERENCES DEPARTMENT
        ON DELETE SET NULL

);

INSERT INTO EMPLOYEE VALUES (1,'Kevin','Cha','kc@sjsu.edu','123 Main St., San Jose, CA 12345',4,1000000);

CREATE TABLE HAS_SCHEDULE
(
    SCHEDULE_ID INTEGER,
    ID INTEGER,
    WORK_HOURS NUMBER NOT NULL,
    WORK_DATE DATE NOT NULL,
    START_TIME TIMESTAMP(2),
    END_TIME TIMESTAMP(2),
    PRIMARY KEY (SCHEDULE_ID, ID),
    FOREIGN KEY (ID) REFERENCES EMPLOYEE
        ON DELETE CASCADE

);

INSERT INTO HAS_SCHEDULE VALUES (1,1,24,DATE '2021-07-26',TO_TIMESTAMP('26-JUL-21 11:20:30.45 AM'),TO_TIMESTAMP('27-JUL-21 11:20:30.45 AM'));

CREATE TABLE RECEIVES_SALARY
(
    SALARY_ID INTEGER,
    ID INTEGER,
    BASE_SALARY NUMBER NOT NULL,
    BONUS NUMBER,
    WORK_HOURS INTEGER,
    TOTAL INTEGER,
    PRIMARY KEY (SALARY_ID, ID),
    FOREIGN KEY (ID) REFERENCES EMPLOYEE
        ON DELETE CASCADE

);

INSERT INTO RECEIVES_SALARY VALUES (1,1,60,5000,24,6440);

CREATE TABLE HAS3_BENEFITS
(
    BID INTEGER,
    ID INTEGER,
    VISIONCARE NUMBER(1,0) NOT NULL,
    MEDICAID NUMBER(1,0) NOT NULL,
    FOODSTAMPS NUMBER(1,0) NOT NULL,
    PRIMARY KEY (BID, ID),
    FOREIGN KEY (ID) REFERENCES EMPLOYEE
        ON DELETE CASCADE
);

INSERT INTO HAS3_BENEFITS VALUES (1,1,1,0,0);

CREATE TABLE APPLY_VACATION_LEAVE
(
    LEAVE_TYPE VARCHAR(50),
    ID INTEGER,
    LEAVE_STATUS VARCHAR(100) NOT NULL,
    START_DATE DATE NOT NULL,
    END_DATE DATE NOT NULL,
    PRIMARY KEY (LEAVE_TYPE, ID),
    FOREIGN KEY (ID) REFERENCES EMPLOYEE
        ON DELETE CASCADE
);

INSERT INTO APPLY_VACATION_LEAVE VALUES ('Vacation',1,'Approved',DATE '2021-07-29',DATE '2021-08-05');

CREATE TABLE ROLE
(
    RID INTEGER PRIMARY KEY,
    ROLE_NAME VARCHAR(100) NOT NULL,
    ROLE_DESC VARCHAR(300) NOT NULL
);

INSERT INTO ROLE VALUES (1,'Leader','Project Leader');

CREATE TABLE HAS2
(
    RID INTEGER,
    ID INTEGER,
    PRIMARY KEY (RID, ID),
    FOREIGN KEY (RID) REFERENCES ROLE,
    FOREIGN KEY (ID) REFERENCES EMPLOYEE
        ON DELETE SET NULL
);
INSERT INTO HAS2 VALUES (1,1);

CREATE TABLE CONTROL_PROJECT
(
    PID INTEGER PRIMARY KEY,
    DID INTEGER NOT NULL,
    P_NAME VARCHAR(200) NOT NULL,
    DUE_DATE DATE NOT NULL,
    STATUS VARCHAR (100)  NOT NULL,
    FOREIGN KEY(DID) REFERENCES DEPARTMENT
        ON DELETE CASCADE
);
INSERT INTO CONTROL_PROJECT VALUES (1,3,'Yelp',DATE '2022-01-01','Implementing');

CREATE TABLE WORKS_ON
(
    RID INTEGER,
    ID INTEGER,
    PID INTEGER,
    LEAD NUMBER(1,0) NOT NULL,
    PRIMARY KEY (RID, ID, PID),
    FOREIGN KEY (RID) REFERENCES ROLE,
    FOREIGN KEY (ID) REFERENCES EMPLOYEE,
    FOREIGN KEY (PID) REFERENCES CONTROL_PROJECT
);
INSERT INTO WORKS_ON VALUES (1,1,1,1);

CREATE TABLE WORK_FOR
(
    DID INTEGER,
    ID INTEGER,
    PRIMARY KEY (DID,ID),
    FOREIGN KEY(DID) REFERENCES DEPARTMENT,
    FOREIGN KEY (ID) REFERENCES EMPLOYEE
        ON DELETE CASCADE
);
INSERT INTO WORK_FOR VALUES (1,1);

CREATE TABLE HAS4_ADDRESS(
                             AID INTEGER NOT NULL ,
                             ID INTEGER NOT NULL ,
                             STREET_ADDRESS VARCHAR(50),
                             CITY VARCHAR(50),
                             STATE VARCHAR(50),
                             ZIPCODE VARCHAR(50),
                             FOREIGN KEY(ID) REFERENCES EMPLOYEE
                                 ON DELETE CASCADE
);
INSERT INTO HAS4_ADDRESS VALUES (1,1,'123 Main St.','San Jose', 'CA', '12345');

COMMIT ;